spring:
  datasource:
    url: jdbc:mariadb://8.141.93.66:3306/lab?useSSL=false&serverTimezone=UTC
    username: root
    password: mima1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 可选：create, validate, none 等
    show-sql: true  # 显示 SQL 查询
    properties:
      hibernate:
        format_sql: true  # 格式化 SQL
logging:
  level:
    com: debug
    sql: debug
    org: debug
  pattern:
    console: "%-3level %C.%M[%line] - %msg%n"
