###

GET localhost:8080/api/reservation/list
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNDczMzU4NywiZXhwIjoxNzM0NzM3MTg3fQ.wpofjPUjS7BuikQHm7FV6xn7GO2TRfglb72TtnhoQio

###

GET localhost:8080/api/reservation/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZSI6IlNVUEVSX0FETUlOIiwiaWF0IjoxNzM1ODQ5ODY0LCJleHAiOjE3MzU4NTM0NjR9.1m1GyV1pxZIsgnZXhyrwpNaV7KIRadeDbqqr4h_kABo


###
POST localhost:8080/api/reservation/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNDczMzU4NywiZXhwIjoxNzM0NzM3MTg3fQ.wpofjPUjS7BuikQHm7FV6xn7GO2TRfglb72TtnhoQio

 {
    "userId": 1,
    "courseId": 13,
    "labId": 19,
    "periodId": 3,
    "weekNumber": 2,
    "weekDay": 1
  }


###
PATCH localhost:8080/api/reservation/34/cancel
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJURUFDSEVSIiwiaWF0IjoxNzM1ODY4ODIyLCJleHAiOjE3MzU4NzI0MjJ9.c_y9a2MibXn4ZBbpAQTt5k6MkY5xIMwec-KYNfjdN_g

###
PATCH localhost:8080/api/reservation/34/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNDczNDk3NCwiZXhwIjoxNzM0NzM4NTc0fQ.yk-m1nSZ2MhBQMKfYOJgc9vvGvuKxu94WBUCvbriTp4

###

PATCH localhost:8080/api/reservation/2/reject

###

GET localhost:8080/api/reservation/admin/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNDczNDk3NCwiZXhwIjoxNzM0NzM4NTc0fQ.yk-m1nSZ2MhBQMKfYOJgc9vvGvuKxu94WBUCvbriTp4

###
GET localhost:8080/api/reservation/week?labId=8&weekNumber=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJURUFDSEVSIiwiaWF0IjoxNzM1ODI0MzMwLCJleHAiOjE3MzU4Mjc5MzB9.wGincr3R8GoyQgJel3KxGUVbAPhCr-L9HjpiffFAj3g
